### PR TITLE
Multiple changes

### PR DESCRIPTION
**Pull request by awnumar**
* Refactoring of functionality into `core` package.
* Addition of `Enclave` objects which store encrypted data.
* Rewrite of signals handling. Should make implementing further data catching much easier.
* Rewrite and simplification of the API.
* Addition of `examples` package.
* Patched data races in interrupt handling functionality.
* Conceal mapped memory from core dumps on OpenBSD.
* Additional functionality added such as safe panicking.
* Disable core dumps by default. Users that want them can enable themselves.
* Use local entropy pool for fast random bytes reading.
* Use a variable sized canary value with `32 <= len(canary) <= ~pagesize`.
* Other optimisations and improvements.
* ...

### CODE REVIEW

**Comment by awnumar** [comment]
To recreate that last one you have to interrupt the program with ^C during that 30s sleep period at the end.

```
^C==================
WARNING: DATA RACE
Read at 0x0000007fd248 by goroutine 11:
  github.com/awnumar/memguard.init.0.func1()
      /home/awn/go/src/github.com/awnumar/memguard/memguard.go:27 +0x51

Previous write at 0x0000007fd248 by goroutine 12:
  command-line-arguments.SocketKey()
      /home/awn/go/src/github.com/awnumar/memguard/memguard.go:43 +0x20e
```

https://github.com/awnumar/memguard/blob/d1e6b99cee65164c05ad1f8fb38491fbaa5ed959/memguard.go#L13-L44

**Comment by awnumar** [comment]
A new test is added based on the races found which uncovers 6 races. This test is disabled on windows since it makes it difficult to send interrupt signals.

**Comment by awnumar** [comment]
Currently able to send an interrupt to ourselves on windows but are prompted with `Terminate batch job (y/N)` and so the test hangs.

**Comment by awnumar** [comment]
Latest patchset eliminated all data races that were detected.

**Comment by awnumar** [comment]
@capnspacehook That's right. Sourcing random bytes is a particularly hot codepath and this change yielded performance benefits of anywhere between 2x and 10x in local tests.

**Comment by capnspacehook** [comment]
Oh awesome! Sounds great. Can't wait till this PR is merged, some really good stuff in here I will definitely be using soon

**Comment by awnumar** [comment]
Getting close to completion now. I can't wait either, so far it's been an excuse for me to procrastinate from exam revision :)

**Comment by capnspacehook** [comment]
I feel that, just got done with exams finally :)

**Comment by awnumar** [comment]
An important little change that was slipped in https://github.com/awnumar/memguard/pull/81/commits/61e6b4f8d777105fb4e663f61dde317c1b3f67e9 is that `NewBuffer` returns a mutable container whereas `NewBufferFromBytes` and `NewBufferRandom` return immutable ones. Also Enclaves decrypt to immutable LockedBuffers.

**Comment by awnumar** [comment]
I'm tentatively considering this ready to merge. Eyes on the code would be appreciated.

**Comment by capnspacehook** [comment]
I can take a look at all the changes this weekend

**Comment by capnspacehook** [comment]
Any reason you removed clone and resize?

**Comment by awnumar** [comment]
Clone was removed because of API bloat. It's fairly easy to recreate its functionality:
```go
b := NewBuffer(8)
c := NewBuffer(b.Size())
c.Copy(b.Bytes())
c.Freeze() // optional
```
Resize required some important decisions to be made regarding mutability and data, decisions that the programmer should probably make themselves. Again the functionality is easy to recreate:
```go
b := NewBuffer(8)
c := NewBuffer(new_size)
c.Copy(b.Bytes())
b.Destroy()
```
I'm thinking of a way to implement streaming into and out of Enclaves which should reduce the need for Resize. (Resize was posed as a solution to #68 originally.)

Do you consider these to be necessary components of the API?

**Comment by capnspacehook** [comment]
I don't consider Clone or Resize to be necessary at all, the reasons you have for removing them are very good ones I think. I was just curious about your reasoning.

I do think while I wouldn't consider it essential, streaming would be nice to have.

**Pull request merged**
